# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['agentnexus/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('agentnexus/prompts/*.txt', 'agentnexus/prompts'),
        ('agentnexus/prompts/fragments/*.txt', 'agentnexus/prompts/fragments'),
        ('agentnexus/skills/builtin/*/workflow.yaml', 'agentnexus/skills/builtin'),
        ('agentnexus/builtin_extensions/*/plugin.yaml', 'agentnexus/builtin_extensions'),
        ('agentnexus/builtin_extensions/*/workflow.yaml', 'agentnexus/builtin_extensions'),
    ],
    hiddenimports=[
        'chromadb',
        'sentence_transformers',
        'jieba',
        'pymupdf',
        'langgraph',
        'langgraph.checkpoint.sqlite',
        'mcp',
        'mcp.client.stdio',
        'mcp.client.streamable_http',
        'openai',
        'rich',
        'typer',
        'yaml',
        'pydantic',
        'pydantic_settings',
        'agentnexus.app.runtime',
        'agentnexus.extensions.manager',
        'agentnexus.skills.profile',
        'agentnexus.skills.registry',
        'agentnexus.skills.runtime',
        'agentnexus.skills.workflow',
        'agentnexus.services.chat',
        'agentnexus.services.skill',
        'agentnexus.tools.providers',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='agentnexus',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
